packages:
  - .
  - ../../nimi/kit
  - ../../nimi/sdks/typescript

allowBuilds:
  esbuild: true
  protobufjs: true

overrides:
  '@nimiplatform/app-tools': link:../../nimi/app-tools
  '@nimiplatform/kit': link:../../nimi/kit
  '@nimiplatform/sdk': link:../../nimi/sdks/typescript
