packages:
  - .
  - ../../nimi-realm/nimi/kit
  - ../../nimi-realm/nimi/sdks/typescript

overrides:
  '@nimiplatform/app-tools': link:../../nimi-realm/nimi/app-tools
  '@nimiplatform/kit': link:../../nimi-realm/nimi/kit
  '@nimiplatform/sdk': link:../../nimi-realm/nimi/sdks/typescript
