packages:
  - .

allowBuilds:
  esbuild: true
  protobufjs: true

overrides:
  '@nimiplatform/sdk': 'file:.nimi/local/music-cohort-2026-09-21/nimiplatform-sdk-0.16.0.tgz'
  '@nimiplatform/kit': 'file:.nimi/local/music-media-cohort-2026-09-21/nimiplatform-kit-0.12.0.tgz'
  '@nimiplatform/app-tools': 'file:.nimi/local/music-cohort-2026-09-21/nimiplatform-app-tools-0.8.0.tgz'
  '@nimiplatform/kit-protected-local-win32-x64': 'file:.nimi/local/music-cohort-2026-09-21/nimiplatform-kit-protected-local-win32-x64-0.12.0.tgz'
